//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int locId { get; set; }
        public string loc_name { get; set; }
    }
}
